server:
  port: 8080
spring:
  cloud:
    config:
      server:
        bootstrap: true
        native:
          searchLocations: file://C://tico//git_tico//micro-services//
  profiles:
    active: native
